---
- name: Temporarily disable screensaver via xset
  become: true
  ansible.builtin.command:
    cmd: "xset s off"
  when: temporarily_disable_screensaver | bool
  changed_when: false
  failed_when: false

- name: Temporarily disable screensaver
  become: true
  ansible.builtin.command:
    cmd: "xset -dpms"
  when: temporarily_disable_screensaver | bool
  changed_when: false
  failed_when: false
